# Name of our action
name: Release

# The event that will trigger the action
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

# what the action will do
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn release
